app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path:     /register
    defaults: { _controller: MedBundle:Default:register }
    options:
        expose: true


api_login_check:
    path: "/login_check"

api:
   resource: "@MedBundle/Resources/config/routing_rest.yml"
   type:     rest
   prefix:   /api
   methods: [POST,GET,DELETE,PUT] 
   options:
        expose: true   

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"   