<?php

namespace MedBundle\Repository;

/**
 * MedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedRepository extends \Doctrine\ORM\EntityRepository
{


}
